application.security.jwt.secret-key=${SECRET_KEY}

spring.datasource.url=jdbc:postgresql://localhost:5432/optica_urbana
spring.datasource.username=postgres
spring.datasource.password=b48V2W0UgG8g

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
Logging.level.org.hibernate.SQL=DEBUG