application.security.jwt.secret-key=${SECRET_KEY}

spring.datasource.url=jdbc:postgresql://dpg-cu8fkud6l47c738hhts0-a.oregon-postgres.render.com:5432/optica_urbana
spring.datasource.username=optica_urbana_user
spring.datasource.password=mVXO53Iy4OkMyyjsaoEpHUxO5HDHLivH

logging.level.org.springframework=ERROR